name: reusable Workflow to Run Tests

on:
  workflow_call:
    inputs:
      tags-of-tests-to-include:
        required: true
        type: string

      tags-of-tests-to-exclude:
        required: false
        type: string
        default: "flaky, failing"

      test-environment:
        required: false
        type: string
        default: "STAGING"

      run-name:
        required: false
        type: string
        default: "CI"

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Unlock secrets
        uses: sliteteam/github-action-git-crypt-unlock@1.2.0
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Test with Maven
        run: >
          mvn
          -DexcludedGroups="${{ inputs.tags-of-tests-to-exclude }}"
          -Dgroups="${{ inputs.tags-of-tests-to-include }}"
          -DTEST_ENV="${{ inputs.test-environment }}"
          -DTRIGGERED_BY="${{ github.event_name }}"
          -DRUN_NAME="${{ inputs.run-name }}"
          clean -B package --file pom.xml

      - name: Generate HTML report from JUnit results
        run: |
          mkdir -p test-reports
          xsltproc junit-frames.xsl target/surefire-reports/TEST-*.xml > test-reports/index.html

      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Automation Test Report"
          to: durgamajji33@example.com
          from: durgaprasadmajji33@example.com
          content_type: text/html
          body: $(cat test-reports/index.html)
